{
 "title": "API Monitoring",
 "tags": [
  "api",
  "observability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Volume by Endpoint (Backend)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"grid-backend\"} |= \"API Request:\" | logfmt [1m])) by (path)"
    }
   ]
  },
  {
   "title": "Request Volume by Endpoint (Admin Backend)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"grid-admin-backend\"} | json | res_statusCode != \"\" [1m])) by (req_url)"
    }
   ]
  },
  {
   "title": "P95 Latency by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {container_name=\"grid-backend\"} |= \"API Request:\" | logfmt | unwrap duration_ms [5m]) by (path)"
    }
   ]
  },
  {
   "title": "Total API Errors (Last 1m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"grid-backend\"} |= \"API Request:\" | logfmt | status >= 400 [1m]))"
    }
   ]
  },
  {
   "title": "Analytical Usage Context",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"grid-backend\"} |~ \"Calculating|Executing|Trace|Generating\" [1h])) by (pkg)"
    }
   ]
  }
 ]
}