import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview',
        'architecture',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      items: [
        'getting-started/installation',
        'getting-started/data-setup',
      ],
    },
    {
      type: 'category',
      label: 'Plugin SDK',
      link: {
        type: 'generated-index',
      },
      items: [
        'sdk/index',
        'sdk/installation',
        'sdk/api-reference',
      ],
    },
    {
      type: 'category',
      label: 'Guides & Examples',
      link: {
        type: 'generated-index',
      },
      items: [
        'examples/rules-engine',
        {
          type: 'category',
          label: 'Grid Analysis Guide',
          items: [{type: 'autogenerated', dirName: 'examples/analysis'}],
        },
      ],
    },
  ],
};

export default sidebars;
